name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/joshua_ryder_i_51_a_7_yy_7_mqa_unsplash_16.jpeg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/frame_3061_x2.svg
  - assets/images/joshua_ryder_i_51_a_7_yy_7_mqa_unsplash_16.jpeg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/frame_306_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/images/joshua_ryder_i_51_a_7_yy_7_mqa_unsplash_16.jpeg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/group_2_x2.svg

